In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [3]:
from google.colab import files
uploaded = files.upload()

Saving dataset9000.csv to dataset9000.csv


In [4]:
df= pd.read_csv("dataset9000.csv")
df.head()

Database Fundamentals Computer Architecture Distributed Computing Systems  \
0          Professional        Not Interested                Not Interested   
1          Professional                  Poor                Not Interested   
2          Professional              Beginner                Not Interested   
3          Professional               Average                Not Interested   
4          Professional          Intermediate                Not Interested   

   Cyber Security      Networking Software Development Programming Skills  \
0  Not Interested  Not Interested       Not Interested     Not Interested   
1  Not Interested  Not Interested       Not Interested     Not Interested   
2  Not Interested  Not Interested       Not Interested     Not Interested   
3  Not Interested  Not Interested       Not Interested     Not Interested   
4  Not Interested  Not Interested       Not Interested     Not Interested   

  Project Management Computer Forensics Fundamentals Technical Communication  \
0     Not Interested                  Not Interested          Not Interested   
1     Not Interested                  Not Interested          Not Interested   
2     Not Interested                  Not Interested          Not Interested   
3     Not Interested                  Not Interested          Not Interested   
4     Not Interested                  Not Interested          Not Interested   

            AI ML Software Engineering Business Analysis Communication skills  \
0  Not Interested       Not Interested    Not Interested       Not Interested   
1  Not Interested       Not Interested    Not Interested       Not Interested   
2  Not Interested       Not Interested    Not Interested       Not Interested   
3  Not Interested       Not Interested    Not Interested       Not Interested   
4  Not Interested       Not Interested    Not Interested       Not Interested   

     Data Science Troubleshooting skills Graphics Designing  \
0  Not Interested         Not Interested     Not Interested   
1  Not Interested         Not Interested     Not Interested   
2  Not Interested         Not Interested     Not Interested   
3  Not Interested         Not Interested     Not Interested   
4  Not Interested         Not Interested     Not Interested   

                     Role  
0  Database Administrator  
1  Database Administrator  
2  Database Administrator  
3  Database Administrator  
4  Database Administrator

In [5]:
df.shape

(9179, 18)

In [6]:
unique_values = df["Role"].unique()

print(unique_values)

['Database Administrator' 'Hardware Engineer'
 'Application Support Engineer' 'Cyber Security Specialist'
 'Networking Engineer' 'Software Developer' 'API Specialist'
 'Project Manager' 'Information Security Specialist' 'Technical Writer'
 'AI ML Specialist' 'Software tester' 'Business Analyst'
 'Customer Service Executive' 'Data Scientist' 'Helpdesk Engineer'
 'Graphics Designer']


In [7]:
df.nunique()

Database Fundamentals               7
Computer Architecture               7
Distributed Computing Systems       7
Cyber Security                      7
Networking                          7
Software Development                7
Programming Skills                  7
Project Management                  7
Computer Forensics Fundamentals     7
Technical Communication             7
AI ML                               7
Software Engineering                7
Business Analysis                   7
Communication skills                7
Data Science                        7
Troubleshooting skills              7
Graphics Designing                  7
Role                               17
dtype: int64

In [8]:
df.isnull().sum()

Database Fundamentals              0
Computer Architecture              0
Distributed Computing Systems      0
Cyber Security                     0
Networking                         0
Software Development               0
Programming Skills                 0
Project Management                 0
Computer Forensics Fundamentals    0
Technical Communication            0
AI ML                              0
Software Engineering               0
Business Analysis                  0
Communication skills               0
Data Science                       0
Troubleshooting skills             0
Graphics Designing                 1
Role                               0
dtype: int64

In [9]:
df=df.dropna()

In [10]:
df.duplicated().sum()

np.int64(1426)

In [11]:
df=df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [12]:
#our target variable is Role
y=df[df.columns[-1]]
X=df[df.columns[:-1]]

In [15]:
df['AI ML'].unique()

array(['Not Interested', 'Poor', 'Beginner', 'Average', 'Intermediate',
       'Excellent', 'Professional'], dtype=object)

In [18]:
df.head()

Database Fundamentals Computer Architecture Distributed Computing Systems  \
0          Professional        Not Interested                Not Interested   
1          Professional                  Poor                Not Interested   
2          Professional              Beginner                Not Interested   
3          Professional               Average                Not Interested   
4          Professional          Intermediate                Not Interested   

   Cyber Security      Networking Software Development Programming Skills  \
0  Not Interested  Not Interested       Not Interested     Not Interested   
1  Not Interested  Not Interested       Not Interested     Not Interested   
2  Not Interested  Not Interested       Not Interested     Not Interested   
3  Not Interested  Not Interested       Not Interested     Not Interested   
4  Not Interested  Not Interested       Not Interested     Not Interested   

  Project Management Computer Forensics Fundamentals Technical Communication  \
0     Not Interested                  Not Interested          Not Interested   
1     Not Interested                  Not Interested          Not Interested   
2     Not Interested                  Not Interested          Not Interested   
3     Not Interested                  Not Interested          Not Interested   
4     Not Interested                  Not Interested          Not Interested   

            AI ML Software Engineering Business Analysis Communication skills  \
0  Not Interested       Not Interested    Not Interested       Not Interested   
1  Not Interested       Not Interested    Not Interested       Not Interested   
2  Not Interested       Not Interested    Not Interested       Not Interested   
3  Not Interested       Not Interested    Not Interested       Not Interested   
4  Not Interested       Not Interested    Not Interested       Not Interested   

     Data Science Troubleshooting skills Graphics Designing  \
0  Not Interested         Not Interested     Not Interested   
1  Not Interested         Not Interested     Not Interested   
2  Not Interested         Not Interested     Not Interested   
3  Not Interested         Not Interested     Not Interested   
4  Not Interested         Not Interested     Not Interested   

                     Role  
0  Database Administrator  
1  Database Administrator  
2  Database Administrator  
3  Database Administrator  
4  Database Administrator

In [19]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [20]:
from sklearn.preprocessing import OrdinalEncoder

In [21]:
categories=['Not Interested', 'Poor', 'Beginner', 'Average', 'Intermediate',
       'Excellent', 'Professional']
enc=OrdinalEncoder(categories=[categories]*X_train.shape[1])
X_train=enc.fit_transform(X_train)
X_test=enc.transform(X_test)

In [22]:
print(X_train)

[[2. 2. 2. ... 2. 2. 2.]
 [4. 4. 4. ... 4. 3. 3.]
 [5. 5. 1. ... 5. 5. 6.]
 ...
 [1. 6. 1. ... 1. 4. 4.]
 [1. 3. 3. ... 3. 3. 6.]
 [0. 0. 0. ... 5. 6. 5.]]


In [23]:
print(X_test)

[[0. 0. 0. ... 1. 0. 0.]
 [4. 5. 5. ... 5. 5. 5.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 3.]
 [1. 1. 1. ... 1. 1. 1.]]


In [28]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [29]:
rf = RandomForestClassifier(
    n_estimators=100,       # Number of trees
    max_depth=10,           # Limit tree depth
    min_samples_split=10,   # Require at least 10 samples to split
    min_samples_leaf=5,     # Require at least 5 samples per leaf
    random_state=42
)
rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, min_samples_leaf=5, min_samples_split=10,
                       random_state=42)

In [30]:
y_pred=rf.predict(X_test)
y_pred

array([15,  3,  5, ..., 15,  1, 11])

In [31]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)*100

100.0

In [32]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)


In [33]:
print(cm)

[[ 84   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  86   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  95   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0  89   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0  77   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0 105   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0  97   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0  97   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0 109   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0  91   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  82   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0 102   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0  84   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0  91   0   0   0]
 [  0 

In [34]:
import joblib
joblib.dump(rf, "skill_prediction_model.pkl")

print("Model saved successfully!")

Model saved successfully!
